# 服务端口号
server:
  port: 8002

# 数据库地址
datasource:
  url: localhost:3306/microservice02

spring:
  application:
    name: microservice-order # 对外暴露的服务名称

  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.java.springcloud.entity
  mapper-locations: # mapper映射文件位置
  - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范


# 客户端注册到eureka服务列表
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: 订单服务-8002  # 定制eureka中status服务名称
    prefer-ip-address: true    # 访问路径可显示ip地址


# 使用actuator来展示项目的基本信息
info:
  author.name: Mr.
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}